### ISSUE TITLE
Line break in inlined script tag

### ISSUE THREAD

**Issue by muuvmuuv** [richardtallent/vite-plugin-singlefile#101]
I see a last line break in my output script tag. Maybe trimRight would fix that?

![image](https://github.com/user-attachments/assets/e5ecbf87-6ce3-4d23-a909-fcafdf02093d)

**Comment by richardtallent** [comment]
Please try the latest version, and if it doesn't work, send a PR with a test to reproduce the issue.

**Comment by muuvmuuv** [comment]
Works now, thanks!
