### ISSUE TITLE
i18n plugin issue

### ISSUE THREAD

**Issue by alphatero** [richardtallent/vite-plugin-singlefile#12]
Hi, I'm using your plugin . It's awesome! But when I used i18n in my project, it got wrong. It can't run normal and console with TypeError. I don't know how to fix this problem. Can you help me?

**Comment by richardtallent** [comment]
Hi,

Please create a repository with a minimal reproduction showing the issue, and file an issue pointing to that repository.

**Comment by alphatero** [comment]
Hi, very thanks for your reply.
My friend tell me this problem is because I used this plugin and vueI18n plugin to build in the same time. When I remove vueI18n plugin setiting in config file, It can be worked normal. So my problem is be fixed.
