### ISSUE TITLE
script replace does not work with different arguments

### ISSUE THREAD

**Issue by mseele** [richardtallent/vite-plugin-singlefile#2]
My html script tag looks like this:

`<script type="module" crossorigin src="/assets/index.21d23eb8.js"></script>`

and will not be replaced. I have a fix that uses a regex so the arguments are not relevant

**Comment by mseele** [comment]
see #3

**Comment by mseele** [comment]
maybe the best way to solve it is by using a html parser and avoid string replacements. But i don't have the time to refactor the code in that way.

**Comment by richardtallent** [comment]
Should be resolved now in 0.5.0... see comments on PR. Thanks again!
