### ISSUE TITLE
[ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by PhentomPT** [richardtallent/vite-plugin-singlefile#23]
Hello,

Following the instructions from the readme lead me to this error
```
error during build:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: `PATH\node_modules\vite-plugin-singlefile\node_modules\chalk\source\index.js
require() of ES modules is not supported.
require() of PATH\node_modules\vite-plugin-singlefile\node_modules\chalk\source\index.js from PATH\node_modules\vite-plugin-singlefile\dist\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename PATH\node_modules\vite-plugin-singlefile\node_modules\chalk\source\index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from PATH\node_modules\vite-plugin-singlefile\node_modules\chalk\package.json.
```

**Comment by richardtallent** [comment]
Hi! Please use 0.7.1, version  0.7.0 was too aggressive in updating a new dependency.

**Comment by PhentomPT** [comment]
@richardtallent waiting for it to be released to npm 👍

**Comment by volarname** [comment]
same problem with 0.8.0

**Comment by ReedSun** [comment]
same problem with 0.9.0, but it is Ok with 0.7.1

**Comment by richardtallent** [comment]
Try setting your application's `type` to `module`, as shown here:

https://github.com/richardtallent/vite-plugin-singlefile-example/blob/54b1d94cb03ae5132b867939a6c649f590005779/package.json#L5

If that becomes an impediment, we'll switch back away from ESM.

**Comment by richardtallent** [comment]
Please try 0.10.0-beta and let me know if it helps. It *should* allow use in both CommonJS and ESM environments.

**Comment by richardtallent** [comment]
0.10.0 has been released.
