### ISSUE TITLE
New config option request: specify what to inline, css or javascript

### ISSUE THREAD

**Issue by ezhlobo** [richardtallent/vite-plugin-singlefile#31]
It will be handy to specify what exactly we should inline. Sometimes it's handy to inline just css and leave javascript to be loaded.

In my use case I build browser extension and it would be great to save a tiny loading time by not doing extra request to load stylesheets. In other hand those extensions prohibit inline scripts and I'd want to keep lazy loading too. 

Even though for my use case I can find solutions, I believe it's logical for this plugin to configure what exactly we want to inline.

**Comment by Greenheart** [comment]
I've got projects where a feature like this would be nice. I think a glob pattern (or RegExp) specifying which files to include would solve this in a nice way.

The default behavior should still be to inline all JS and CSS, like the name of the plugin.
However, we could add an optional parameter `inlinePattern` which could be a glob pattern or RegExp that is tested against all asset file names (JS and CSS). If an asset matches the `inlinePattern`, it gets inlined.

Suggested library to test a string against a glob pattern: https://github.com/micromatch/micromatch

**Comment by richardtallent** [comment]
Please try 0.10.0-beta, I've added this option.

**Comment by richardtallent** [comment]
0.10.0 has been released.
