### ISSUE TITLE
Manipulate the .html files in `generateBundle` hook instead of `transformIndexHtml`

### ISSUE THREAD

**Issue by m4rvr** [richardtallent/vite-plugin-singlefile#32]
Hey! I needed your plugin together with UnoCSS to generate one index.html where everything is inlined.
Because UnoCSS replaces the placeholders in the `generateBundle` hook it didn't generate the CSS correctly. The CSS from UnoCSS wasn't replaced and the placeholders where still in the code.

So I tried to fix this and tested a bit with the hooks and got a working plugin which 1. generates the bundle correctly and 2. deletes the entries of the `bundle` so they don't get generated into the `assets` dir.

The code is probably not very perfect and could be adjusted. I copied your Regex from your plugin.
With this code it should be possible to generate multiple `.html` files with inlined assets. Not sure if this works when you use `transformIndexHtml`? It's also my first plugin haha.

Keep in mind it doesn't include the extra functions like the custom build config yet. :)

```ts
{
  name: 'singlefile',
  apply: 'build',
  enforce: 'post',
  generateBundle: (_, bundle) => {
    const htmlFiles = Object.keys(bundle).filter((i) => i.endsWith('.html'))
    const cssAssets = Object.keys(bundle).filter((i) => i.endsWith('.css'))
    const jsAssets = Object.keys(bundle).filter((i) => i.endsWith('.js'))

    for (const name of htmlFiles) {
      const htmlChunk = bundle[name]
      let replacedHtml = htmlChunk.source

      for (const jsName of jsAssets) {
        const jsChunk = bundle[jsName]
        const reScript = new RegExp(
          `<script type="module"[^>]*?src="[\./]*${jsChunk.fileName}"[^>]*?></script>`
        )

        const code = `<script type="module">\n//${jsChunk.fileName}\n${jsChunk.code}\n</script>`
        replacedHtml = replacedHtml.replace(reScript, code)
        delete bundle[jsName]
      }

      for (const cssName of cssAssets) {
        const cssChunk = bundle[cssName]
        const reCSS = new RegExp(
          `<link rel="stylesheet"[^>]*?href="[\./]*${cssChunk.fileName}"[^>]*?>`
        )
        const code = `<style type="text/css">\n${cssChunk.source}\n</style>`
        replacedHtml = replacedHtml.replace(reCSS, code)
        delete bundle[cssName]
      }

      htmlChunk.source = replacedHtml
    }
  }
}
```

Let me know what you think! :)

**Comment by richardtallent** [comment]
Great find! I'm not sure why I didn't use `generateBundle` before, I guess I was focusing on Vite-related hooks rather than rollup. Please try 0.10.0-beta and let me know if it works as intended.

**Comment by richardtallent** [comment]
0.10.0 has been released, which implements this

**Comment by kidonng** [comment]
I encountered the same issue with UnoCSS, so I [rolled a simpler one my own](https://github.com/kidonng/xuann.wang/commit/8810ff5a7c1c57793dcfb99a9502a1b1b294a256#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890ddR10-R37) earlier this year, but never got to submit the issue here. Glad to see it implemented, I've now switched to this plugin 🚀
