### ISSUE TITLE
Regular expression to match the script tag to inline is too specific

### ISSUE THREAD

**Issue by koriolis** [richardtallent/vite-plugin-singlefile#37]
Hi.
So I came across this issue because my particular vite configuration outputs the script tags as:

`<script async type="module" crossorigin src="/assets/whatever.cffa7373.js"></script>`

This is not covered by the regular expression at L33
https://github.com/richardtallent/vite-plugin-singlefile/blob/3d15a59e53ef6afbae48dd7aa4f2c7d10ddc69c8/src/index.ts#L33 

This Regex looks for a `<script>` tag that starts with type="module" and then contains a `src` attribute with the filename.

AFAICT the only thing the script should be looking for is a `<script>`  tag that contains the `src` attribute with the filename we want to embed. so that Regex should be **maybe** something like:
`<script[^>]*?src="[\./]*${o.fileName}"[^>]*?></script>`

This is how I sorted my use case which may be different than the generic use case you're trying to solve, so this solution may not please everybody, although I would think that's generic enough though.

**Comment by richardtallent** [comment]
Please try 0.10.0-beta and let me know if it helps.

**Comment by richardtallent** [comment]
0.10.0 has been released, this should be fixed now.
