### ISSUE TITLE
Inlining other assets as SVG's, PNG's and TTF's

### ISSUE THREAD

**Issue by MaiTheLord** [richardtallent/vite-plugin-singlefile#48]
Title is self explanatory. any plans to implement something like this?

**Comment by richardtallent** [comment]
Since part of using this plug-in entails setting the "assetsInlineLimit" ridiculously high, all imported binary files in the Assets folder should be inlined as base64 data URLs, which means they will end up in the final HTML bundle.

Details:

https://vitejs.dev/guide/assets.html
