### ISSUE TITLE
Inline SVG assets

### ISSUE THREAD

**Issue by tk-100** [richardtallent/vite-plugin-singlefile#52]
Dear maintainer,

first of all, thanks for your great plugin! I would like to export vue apps, containing svg graphics. Unfortunately, these files don't get inlined and I receive messages during build like:

~~~
rendering chunks (1)...WARNING: asset not inlined: assets/games.e8418186.svg
~~~

Other graphic formats, like png are handled correctly. 
In order to reproduce this error, I created a minimum demo project https://codeberg.org/MintApps/test

I would really appreciate any tips/help,
Thomas

**Comment by tk-100** [comment]
After some more reading, I can answer my own question:

Vite itself does not support inlining of SVG graphics, see the discussion https://github.com/vitejs/vite/issues/1197. I'm afraid that can't be solved in your package.

Workarounds:
- Use the [vite-svg-loader](https://github.com/jpkleemans/vite-svg-loader), which can be easily combined with your plugin
- Copy the contents of the SVG-file into the HTML-Template

You might want to include a note in your README.

**Comment by fweth** [comment]
Same also for the favicon (which is not in assets) :)
