### ISSUE TITLE
replaceScript method is "__VITE_PRELOAD__" replace first only.

### ISSUE THREAD

**Issue by juner** [richardtallent/vite-plugin-singlefile#55]
[replace()](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/replace) is replace first target.

https://github.com/richardtallent/vite-plugin-singlefile/blob/5516a454d54d297219881d4e73df22a2a0b4560f/src/index.ts#L23-L29

It seems to me that [replaceAll()](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) should be used.

https://github.com/richardtallent/vite-plugin-singlefile/blob/5516a454d54d297219881d4e73df22a2a0b4560f/src/index.ts#L26

↓

```ts
	const newCode = scriptCode.replaceAll(preloadMarker, "void 0")
```

**Comment by richardtallent** [comment]
Change made, will be in the next release

**Comment by juner** [comment]
@richardtallent thank you very much!

**Comment by juner** [comment]
The commit containing this correspondence is here.
https://github.com/richardtallent/vite-plugin-singlefile/commit/d3589eec2b6d9309f7732ed9ed8eff0c3761f112

**Comment by juner** [comment]
The commit containing this correspondence is here.
https://github.com/richardtallent/vite-plugin-singlefile/commit/886cdd720b85fb4fc34f1dc2bb56eb3a1e24195c
