### ISSUE TITLE
Statements in Readme.md about Limitations are wrong

### ISSUE THREAD

**Issue by 8-Lambda-8** [richardtallent/vite-plugin-singlefile#67]
- localStorage is available (Tested on firefox, chrome and edge)

- the file:// protocol is a secure context (https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)

(and FileSystem API would need a secure context :smile:)

**Comment by richardtallent** [comment]
Thanks! I've updated the README and added some tests to the accompanying test app.
