### ISSUE TITLE
Preload in newer Vite version breaks this

### ISSUE THREAD

**Issue by richardtallent** [richardtallent/vite-plugin-singlefile#7]
In newer versions of Vite, a `vendor` file is generated and imported from the main script file regardless of other options. This seems to be non-trivial to unwire, since the imports from that vendor file are aliased when imported.

I don't know if this is something that is under Vite's control or Rollup's, but somehow, we need a way to disable all forms of code-splitting so we have a single JavaScript output.

**Comment by richardtallent** [comment]
I found a workaround -- adding a `rollupOptions.outputOptions.manualChunks` config option to force all chunks into a single file. Added it to the README.

**Comment by Rundik** [comment]
It still doesn't work

```html
<script type="module">
//assets/index.abf9c88a.js
var e;import{C as t,p as o,o as n}from"./vendor.0e739c8d.js";...</script>
<link rel="modulepreload" href="/assets/vendor.0e739c8d.js">
```

```js
import { defineConfig } from "vite";
import { viteSingleFile } from "vite-plugin-singlefile";

export default defineConfig({
  plugins: [viteSingleFile()],
  build: {
    cssCodeSplit: false,
    assetsInlineLimit: 100000000,
    rollupOptions: {
      outputOptions: {
        inlineDynamicImports: true,
        manualChunks: () => "main.js",
      },
    },
  },
})
```

```json
{
  "scripts": {
    "dev": "vite --port 8080",
    "build": "vite build",
    "serve": "vite preview --port 8080"
  },
  "devDependencies": {
    "vite": "^2.1.5"
  }
}
```

**Comment by richardtallent** [comment]
I updated everything and tested this morning, and it worked properly. I'm using

- vite 2.1.5
- vue 3.0.11
- @vue/compiler-sfc 3.0.11
- vue-router 4.0.6
- @vitejs/plugin-vue@1.2.1

I do see some differences in our `vite.config.js` files, I believe your issue is that you have `rollupOptions.outputOptions` instead of `rollupOptions.output`:

```js
export default defineConfig({
	plugins: [vue(), viteSingleFile()],
	build: {
		target: "esnext",
		assetsInlineLimit: 100000000,
		chunkSizeWarningLimit: 100000000,
		cssCodeSplit: false,
		sourcemap: false,
		brotliSize: false,
		rollupOptions: {
			inlineDynamicImports: true,
			output: {
				manualChunks: () => "everything.js",
			},
		},
	},
})
```

So, it appears our documentation is a bit out of date. I'll address that now. Thanks!

**Comment by Greenheart** [comment]
@richardtallent I can confirm your suggested solution from https://github.com/richardtallent/vite-plugin-singlefile/issues/7#issuecomment-814868961 works for project using `svelte`.

Thanks for creating this plugin! ✨

Here is my `vite.config.js`

```js
import { defineConfig } from 'vite'
import svelte from '@sveltejs/vite-plugin-svelte'
import { viteSingleFile } from 'vite-plugin-singlefile'

export default defineConfig({
    plugins: [svelte(), viteSingleFile()],
    build: {
        target: 'esnext',
        assetsInlineLimit: 100000000,
        chunkSizeWarningLimit: 100000000,
        cssCodeSplit: false,
        sourcemap: false,
        brotliSize: false,
        rollupOptions: {
            inlineDynamicImports: true,
            output: {
                manualChunks: () => 'everything.js',
            },
        },
    },
})

```
