### ISSUE TITLE
Doesn't work with minify: false

### ISSUE THREAD

**Issue by rcoopr** [richardtallent/vite-plugin-singlefile#72]
The following regex matches both cases - minified and not - however I have only tested it for a couple of individual use cases

```ts
/(\s*<script type="module" crossorigin>\s*)\(function[\s\S]*?\}\)\(\);/
```

The removed segment is `\(\)\{` after `function` - when not minified, the polyfill is a named function

**Comment by richardtallent** [comment]
Thanks, fixed in 0.13.5!
