### ISSUE TITLE
manifest.json usage in index.html

### ISSUE THREAD

**Issue by mantaspuidokas** [richardtallent/vite-plugin-singlefile#87]
I'm trying to include `manifest.json`  file inside the `index.html`, but I'm getting CORS error:

![image](https://github.com/richardtallent/vite-plugin-singlefile/assets/86296076/a1395c6f-a4ba-4ae1-85ca-69bbc7f2e29e)

Is manifest file usage possible with this plugin?

**Comment by richardtallent** [comment]
Sounds like you would have to embed it manually as a data URL rather than just importing it and having vite bundle it directly. Closing, since this is a CORS issue, not something specific to this plugin.
