### ISSUE TITLE
can not use it with vue-router

### ISSUE THREAD

**Issue by zuishuaicc** [richardtallent/vite-plugin-singlefile#92]
my project use vue3+vue-router,then install this plugin,after build my project ,i can open the index.html page.but open the router page failed,

**Comment by hololeo** [comment]
i have this problem too. it seems just loading an index.html page wont work.

**Comment by richardtallent** [comment]
I've used this with `vue-router` since I created it, since I'm a Vue developer. But, as mentioned in the README, you must use **hash-based** routing, not the Web History API. See:

https://router.vuejs.org/guide/essentials/history-mode

**Comment by zuishuaicc** [comment]
ok，thanks

**Comment by zuishuaicc** [comment]
> I've used this with `vue-router` since I created it, since I'm a Vue developer. But, as mentioned in the README, you must use **hash-based** routing, not the Web History API. See:
> 
> https://router.vuejs.org/guide/essentials/history-mode

ok，thanks
