### ISSUE TITLE
Inlining small scripts

### ISSUE THREAD

**Issue by aminya** [richardtallent/vite-plugin-singlefile#94]
I want to inline the small scripts (e.g. files that are under 1 KB) into my HTML. Vite (and Astro) create very small files for different components, which could be inlined instead to avoid the overhead of another HTTP request.

Is there a way to specify a size limit for the max threshold of inlining? 

```jsx
 [vite] dist/_astro/logo.De6d2APk.svg        0.46 kB │ gzip:  0.26 kB
 [vite] dist/_astro/Component1.DRflpVO5.js   0.14 kB │ gzip:  0.14 kB
 [vite] dist/_astro/Component2.DK5iz3Tl.js   0.74 kB │ gzip:  0.45 kB
 [vite] dist/_astro/client.BhZioPRu.js       0.90 kB │ gzip:  0.56 kB
 [vite] dist/_astro/solid.DJlj9KZv.js        10.03 kB │ gzip:  4.19 kB
```

**Comment by Greenheart** [comment]
I this could be closed as out of scope for this project, based on the following paragraph from the project [README](https://github.com/richardtallent/vite-plugin-singlefile?tab=readme-ov-file#why):

> This is a single file plugin. As in, it creates one HTML file and no other files. Hence the name. So, this either will not work or will not be optimized for apps that require multiple "entry points" (HTML files). Please see issue #51 for details. Issues opened requesting multiple entry points will be closed as wontfix.

**Comment by richardtallent** [comment]
This is outside the scope of this plugin, and would be best handled by adjusting how Rollup works.
