### ISSUE TITLE
Option for css minimization target

### ISSUE THREAD

**Issue by Juratbek** [richardtallent/vite-plugin-singlefile#99]
I am building a samsung app and single html file with all codes is awesome for me

But I can't use all css features because I need to support old TVs

When I style a block with following styles
`
left: 0;
right: 0;
top: 0;
bottom: 0;
`

it is replacing these styles with `inset:0;`

I need to disable this or specify the css build target

**Comment by ineo6** [comment]
See https://github.com/evanw/esbuild/issues/1925

With vite, you can set cssTarget，`ios13` is my config，you can replace by your tv os version.

```
  build: {
    target: 'es2015',
    cssTarget: ['es2015', 'ios13'],
  },
```

**Comment by richardtallent** [comment]
As mentioned above, this is a Vite thing, not a plugin thing.

**Comment by Juratbek** [comment]
Thank you :)
